CREATE DATABASE TODOLIST
USE todolist

-- CREACION DE TABLAS
CREATE TABLE Todos(
	todoID NVARCHAR(300) NOT NULL,
	description NVARCHAR(200) NOT NULL,
	estatus INT NOT NULL,
	usuarioId INT NOT NULL, 
)

CREATE TABLE Usuarios(
	usuarioid INT IDENTITY NOT NULL,
	correo NVARCHAR(100) NOT NULL,
	password NVARCHAR(200) NOT NULL,
	estatus INT NOT NULL,
	roleid INT NOT NULL
);


CREATE TABLE Roles(
	roleid INT NOT NULL,
	roleName NVARCHAR(100) NOT NULL,
)
GO

-- INTEGRIDAD (PK)
ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY(roleid);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY(usuarioid)
ALTER TABLE TODOS ADD CONSTRAINT PK_TODOS PRIMARY KEY(todoid)

-- INTEGRIDAD (FK)
ALTER TABLE USUARIOS 
ADD CONSTRAINT FK_USUARIOS_ROLE
FOREIGN KEY(roleid) REFERENCES Roles(roleid)

ALTER TABLE TODOS
ADD CONSTRAINT FK_TODOS_USUARIOS
FOREIGN KEY(usuarioid) REFERENCES Usuarios(usuarioid)
go

-- INSERCION DE LOS ROLES
INSERT INTO ROLES VALUES(1, 'ADMIN_ROLE');
INSERT INTO ROLES VALUES(2, 'USER_ROLE');